apiVersion: apps/v1
kind: Deployment
metadata:
  name: javatest
  labels:
    app: javatest
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: javatest
  template:
    metadata:
      labels:
        app: javatest
    spec:
      containers:
      - name: {{ .Values.image.name}}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.container.port }}
